
services:


  postgresql:
    image: postgres:17
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: journalapp
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data:rw


  keycloak:
    image: quay.io/keycloak/keycloak
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - "8082:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql/keycloak?currentSchema=keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: 'http://localhost:8082'
      KC_PROXY: 'edge'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgresql