package be.helha.journalapp.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents a comment made by a user on an article.
 * This entity is mapped to a database table and includes fields for content, publication date,
 * and relationships to the associated user and article.
 */
@Entity
@Data
@Table(name = "Comments")
public class Comment {

    /**
     * The unique identifier for the comment.
     * It's auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long commentId;

    /**
     * The content of the comment.
     */
    private String content;

    /**
     * The publication date of the comment.
     */
    private String publicationDate;

    /**
     * Many-to-One relationship with {@link User}.
     * A comment is authored by a single user.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false) // Foreign key to User
    private User user;

    /**
     * Many-to-One relationship with {@link Article}.
     * A comment belongs to a single article.
     */
    @ManyToOne
    @JoinColumn(name = "article_id", nullable = false) // Foreign key to Article
    private Article article;
}
