package be.helha.journalapp.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents an image entity in the application.
 * This entity is mapped to a database table and includes fields to store image data and its relationship with an article.
 */
@Entity
@Data
public class Image {

    /**
     * The unique identifier for the image.
     * It's auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long imageId;

    /**
     * The binary data of the image, stored as a byte array.
     * The `@Lob` annotation indicates that the database should store this field as a Large Object.
     */
    @Lob
    private byte[] imagePath; // Used to store binary data (such as an image)

    /**
     * Many-to-One relationship with {@link Article}.
     * Each image belongs to a single article.
     */
    @ManyToOne
    @JoinColumn(name = "article_id", nullable = false) // Foreign key to Article
    private Article article;
}
