package be.helha.journalapp.model;

import jakarta.persistence.*;
import lombok.Data;
import java.util.List;

/**
 * Represents a role within the application.
 * <p>
 * This entity is mapped to a database table and stores information about roles, including
 * a unique role identifier, the name of the role, and its corresponding Keycloak role ID.
 * It is used to manage user roles and is linked to user entities.
 */
@Entity
public class Role {

    /**
     * The unique identifier for this role.
     * <p>
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long roleId;

    /**
     * The name of the role, such as "admin", "user", etc.
     */
    private String roleName;

    /**
     * The unique identifier for this role within Keycloak.
     */
    private String keycloakRoleId;

    /**
     * Default constructor for the Role entity.
     * <p>
     * It is required by JPA.
     */
    public Role() {}

    /**
     * Constructor for creating a new Role entity with a role name and a Keycloak role ID.
     *
     * @param roleName       The name of the role.
     * @param keycloakRoleId The Keycloak identifier for the role.
     */
    public Role(String roleName, String keycloakRoleId) {
        this.roleName = roleName;
        this.keycloakRoleId = keycloakRoleId;
    }

    /**
     * Gets the unique identifier of this role.
     *
     * @return The unique role identifier.
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * Sets the unique identifier of this role.
     *
     * @param roleId The new role identifier.
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * Gets the name of this role.
     *
     * @return The role name.
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * Sets the name of this role.
     *
     * @param roleName The new role name.
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * Gets the unique identifier of the role in Keycloak.
     *
     * @return The Keycloak role identifier.
     */
    public String getKeycloakRoleId() {
        return keycloakRoleId;
    }

    /**
     * Sets the unique identifier of the role in Keycloak.
     *
     * @param keycloakRoleId The new Keycloak role identifier.
     */
    public void setKeycloakRoleId(String keycloakRoleId) {
        this.keycloakRoleId = keycloakRoleId;
    }

    /**
     * Returns a string representation of the Role object.
     *
     * @return A string representation of the role.
     */
    @Override
    public String toString() {
        return "Role{" +
                "roleId=" + roleId +
                ", roleName='" + roleName + '\'' +
                ", keycloakRoleId='" + keycloakRoleId + '\'' +
                '}';
    }
}